theme: jekyll-theme-architect

title: [javaserverfaces-spec]
description: [GlassFish's Implementation for JavaServer(TM) Faces]

# sidebar links url
links:
  source: https://github.com/javaee/javaserverfaces-spec
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

