theme: jekyll-theme-architect

title: [javaserverfaces-spec]
description: [JavaServer(TM) Faces Specification]

# sidebar links url
links:
  source: http://jsf.java.net/
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

